project:
  type: website

resources:
  - CNAME

website:
  title: "ACC Baseball Explorer"
  google-analytics: "G-73DDQNMS2L"
  page-footer:
    center: |
      Created by Hana Baskin

      **Connect:** <hana.baskin@gmail.com>

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: metrics.qmd
        text: Metrics
      - href: about.qmd
        text: About
      - href: whats-new.qmd
        text: What's New

    right:
      - text: GitHub
        href: https://github.com/hvb210/accbaseballr
        target: _blank
      - text: R package
        href: https://cran.r-project.org/web/packages/accbaseballr/index.html
        target: _blank


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

publish:
  gh-pages

